modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"

[[mods]]
modId="spasm"
version="0.0.2"
displayName="Structureless Peaceful Assist Superflat Mod"
displayURL="https://github.com/bopel-maki-macohi/spasm"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Maki"

# Start of user code block mod configuration
# End of user code block mod configuration


# Start of user code block custom mixins
# End of user code block custom mixins

[[dependencies.spasm]]
    modId="neoforge"
    type="required"
    versionRange="[26.1.2.71,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.spasm]]
    modId="minecraft"
    type="required"
    versionRange="[26.1.2]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration